### ISSUE TITLE
Script de carga de anuncios

### ISSUE THREAD

**Issue by ardiadrianadri** [ardiadrianadri/keepCodingPractice#7]
Tenemos que programar un script que realice la primera carga en BD

**Comment by sherlock722** [comment]
en desarrollo

**Comment by sherlock722** [comment]
Se sube script de carga de bbdd. También se ha modificado el packaje.json para que el script pueda ser lanzado con npm. Es necesario instalar el modulo async.

**Comment by ardiadrianadri** [comment]
Javi, no entiendo algunas cosas de tu script de carga de base de datos.

Lo primero que me llama la atención son las entidades Anuncio y Usuario:
```
//Modelos
var Anuncio = require ('../models/Anuncio.js');
var Usuario = require ('../models/Usuario.js');
```

Aqui declaras dos entidades modelos que las requireres de dos rutas que no existen en el proyecto. Una de ellas es anuncios que no está programada pero, la otra, es usuario que sí que ya está programada en la ruta back/entities/users.js. Mi pregunta es ¿Por que no usas la entidad users.js que es la que utilizamos para los servicios de singin y login? 

Luego, si creas una entidad modelo Anuncios, que la vamos a necesitar, ¿Por que no la creas ya en la carpeta entities y de esta forma la podemos aprovechar para los servicios restantes?

Esto me lleva a pensar que, o bien no estás de acuerdo con la forma en la que he estructurado el proyecto o bien no entiendes el código que hay subido al repositorio. Da igual cual de las dos razones es la que te ha llevado a utilizar dos modelos no integrados en el desarrollo, la solución es la misma; hablar. Si no estás de acuerdo con la estructura del código la podemos cambiar por otra en la estemos los dos deacuerdo. Si no entiendes el código subido y como funciona me siento contigo una tarde y te lo explico. Sin problemas.

Luego, otra cosa que he visto, es que mezclas " con ' en el mismo fichero y que hay variables declaradas que no usas. Esos fallos son sintomas de que no pasas el jsHint como nos pidieron en la práctica. Si necesitas ayuda para instalar el jsHint o para aprender cómo usarlo dilo y también te puedo echar una mano con esto.
